### ISSUE TITLE
Not sure if those are saveBits

### ISSUE THREAD

**Issue by Kawa-oneechan** [EricOakford/SCI-Decompilation-Archive#7]
I was looking through the KQ4 decompile, and came to a conclusion.

Lines like this don't make much sense:
```clojure
(= saveBits (Print 51 9 #font smallFont #at -1 5 #time 12))
```
`saveBits` is only ever set, never actually used, _and_ its name implies it's a little screenshot of the stuff below the window instead of a control's value or a boolean.

Was KQ4 just that weirdly written? Did `Print` at one point return something other than true, false, or a control value?

**Comment by EricOakford** [comment]
Yes, I think the idea is that it saves the bits under the window so it can restore them, especially when #dispose is invoked to allow for the action to continue while the dialog is shown.

In the INN demo, there is an actual DoDisplay object, and it does indeed save the bits underneath the text. Although it uses the DIsplay kernel function rather than Print, it appears to work in much of the same way.

saveBits is the best name I could think of, given that DoDisplay uses that name as a property.

And yeah, KQ4 was very weirdly written, being that it was the first SCI game.

**Comment by Kawa-oneechan** [comment]
If that's the idea, then... where are these locals _used_ afterwards?

**Comment by EricOakford** [comment]
It turns out, #dispose is used to clear any modeless dialog, but keep the current dialog object, which is assigned to the variable in question.
So it looks like a more accurate name would be printObj, since it's the object that's being allowed to remain until cls is invoked.
I've made the correction for LSL2 and KQ4. Other games will follow.

**Comment by Kawa-oneechan** [comment]
So if you have `#dispose`, it returns the dialog, and it returns true, false, or a control value otherwise? That makes sense, I guess. Just leaves the question what KQ4 is saving that reference for 99% of the time it appears 😺
